### ISSUE TITLE
Work outside of Symfony

### ISSUE THREAD

**Issue by dgram** [massiveart/MassiveSearchBundle#109]
Hey,

i want to use this bundle outside of Symfony - in that case for ZendFramework.
Is there an easy way to work without the whole symfony mvc in use?

regards thx

**Comment by wachterjohannes** [comment]
the only way I would see is to extract the namespace `Massive\Bundle\SearchBundle\Search` into an own component and use it here. but I don't think that will be done in the nearer future. @chirimoya what do you tink?

**Comment by dgram** [comment]
okay thx for your answer. i think i have found an option, someone develop an symfonybridge for zendframework, i've try to load the MassiveSearchBundle within the bridge, if someones interested in the bridge see here [SymfonyBridge](https://zfmodules.com/blanchonvincent/SymfonyBridgeModule)

**Comment by wachterjohannes** [comment]
@dgram thanks for the information. i will close this issue - but if you need some help feel free to ask here or create a new issue
