### ISSUE TITLE
How to create a new searchAdapter?

### ISSUE THREAD

**Issue by crevillo** [massiveart/MassiveSearchBundle#116]
Hi there. i'm trying to create  new adapter, in this case to make it work with Algolia. i've created the services but problem is when i set the new adapter in the config like 
```yaml
# MassiveSearch Configuration
massive_search:
    adapter: algolia
```

When i do this i get an error like
```
In EnumNode.php line 46:
                                                                                                                              
  The value "algolia" is not allowed for path "massive_search.adapter". Permissible values: "zend_lucene", "elastic", "test"  
                                                                                                                             
```

so, is there any way to add another adapter or to modify that list of possible values?

Thanks in advance.

**Comment by wachterjohannes** [comment]
you cannot extend the configuration but to use your custom adapter you have to set the alias `massive_search.adapter` for your service.

i will close the issue - but if you don't think its fixed feel free to reopen it
