### ISSUE TITLE
Please update https://massivesearchbundle.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by kfrohwein** [massiveart/MassiveSearchBundle#125]
Please update the site to the latest GIT version https://massivesearchbundle.readthedocs.io/en/latest/

I had a hard time to figure how the Elastic Search configuration is because the latest github Docpage is not  used for your doc site linked from the readme. Lost some hours because of you :P Glad I asked Alex about it!

**Comment by danrot** [comment]
Done :slightly_smiling_face:
