### ISSUE TITLE
Rebuild index leaks memory

### ISSUE THREAD

**Issue by christianbader** [massiveart/MassiveSearchBundle#62]
When executing the index rebuild command on ~ 10.000 Contacts:
app/console massive:search:index:rebuild

a OutOfMemoryException accurs:
[Symfony\Component\Debug\Exception\OutOfMemoryException]                                  
Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65552 bytes)

**Comment by dantleech** [comment]
Using Elastic? (I think this would probably take years with Zend Lucene)

**Comment by danrot** [comment]
@dantleech Doesn't matter if zend lucene or elastic, I am already looking at it.

**Comment by dantleech** [comment]
Addressed by #74
