### ISSUE TITLE
Symfony 3 Support

### ISSUE THREAD

**Issue by benbender** [massiveart/MassiveSearchBundle#81]
I just tried to install your promising package on a symfony 3.0.4 installation and sadly failed because of the dependency on "symfony/property-access ~2.4". Are there any plans to support sf3 in the near future?

Thanks for your awesome work!

**Comment by wachterjohannes** [comment]
yes we are also working on symfony 3.0 support for sulu (see issue https://github.com/sulu/sulu/issues/2106). i have currently no idea how much work it would be to upgrade this bundle. i will take a look today and give you information afterwards.

**Comment by benbender** [comment]
Thanks for the prompt response - I did a quicktest in the meantime (aliasing versions in composer via "symfony/property-access": "3.0 as 2.8"). Here are the results.

With this simple mapping:
```
<massive-search-mapping xmlns="http://massive.io/schema/dic/massive-search-mapping">
    <mapping class="AppBundle\Entity\Post">
        <index name="post" />
        <id property="id" />
        <fields>
            <field name="title" type="string" />
            <field name="body" type="string" />
        </fields>
    </mapping>
</massive-search-mapping>

```
I got the following exception:

> [Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException]
>   Neither the property "post" nor one of the methods "getPost()", "post()", "isPost()", "hasPost()", "__get()" exist and have public access in class "AppBu
>   ndle\Entity\Post".
> 
> 
> Exception trace:
>  () at /Users/bb/Desktop/c4a/vendor/symfony/property-access/PropertyAccessor.php:379
>  Symfony\Component\PropertyAccess\PropertyAccessor->readProperty() at /Users/bb/Desktop/c4a/vendor/symfony/property-access/PropertyAccessor.php:272
>  Symfony\Component\PropertyAccess\PropertyAccessor->readPropertiesUntil() at /Users/bb/Desktop/c4a/vendor/symfony/property-access/PropertyAccessor.php:81
>  Symfony\Component\PropertyAccess\PropertyAccessor->getValue() at /Users/bb/Desktop/c4a/vendor/massive/search-bundle/Search/Metadata/FieldEvaluator.php:106
>  Massive\Bundle\SearchBundle\Search\Metadata\FieldEvaluator->getFieldValue() at /Users/bb/Desktop/c4a/vendor/massive/search-bundle/Search/Metadata/FieldEvaluator.php:60
>  Massive\Bundle\SearchBundle\Search\Metadata\FieldEvaluator->getValue() at /Users/bb/Desktop/c4a/vendor/massive/search-bundle/Search/ObjectToDocumentConverter.php:79
>  Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter->objectToDocument() at /Users/bb/Desktop/c4a/vendor/massive/search-bundle/Search/SearchManager.php:136
>  Massive\Bundle\SearchBundle\Search\SearchManager->index() at /Users/bb/Desktop/c4a/vendor/massive/search-bundle/Command/ReindexCommand.php:219
>  Massive\Bundle\SearchBundle\Command\ReindexCommand->reindexClass() at /Users/bb/Desktop/c4a/vendor/massive/search-bundle/Command/ReindexCommand.php:149
>  Massive\Bundle\SearchBundle\Command\ReindexCommand->execute() at /Users/bb/Desktop/c4a/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
>  Symfony\Component\Console\Command\Command->run() at /Users/bb/Desktop/c4a/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:807
>  Symfony\Component\Console\Application->doRunCommand() at /Users/bb/Desktop/c4a/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
>  Symfony\Component\Console\Application->doRun() at /Users/bb/Desktop/c4a/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/bb/Desktop/c4a/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
>  Symfony\Component\Console\Application->run() at /Users/bb/Desktop/c4a/bin/console:29
> <command>

`

I have no idea why the heck the package wants to access a field named "post". Maybe it's a startingpoint for your research!

Thanks in advance!
